// NSE symbol → Angel One token map, pre-built from ScripMaster.
// Generated by: python3 scripts/build-scrip-tokens.py (run to refresh).
// Covers all NSE equity (-EQ) series: ~9500 stocks.

import scripTokens from './scrip-tokens.json';

const TOKEN_MAP = scripTokens as Record<string, string>;

export function resolveToken(symbol: string): string | null {
  return TOKEN_MAP[symbol] ?? null;
}

export async function getSymbolToToken(): Promise<Map<string, string>> {
  return new Map(Object.entries(TOKEN_MAP));
}

export function getAllTokens(): Record<string, string> {
  return TOKEN_MAP;
}
