export interface StockInfo {
  ticker: string;
  name: string;
  sector: string;
}

export const NIFTY_50: StockInfo[] = [
  { ticker: 'ADANIENT', name: 'Adani Enterprises', sector: 'Diversified' },
  { ticker: 'ADANIPORTS', name: 'Adani Ports & SEZ', sector: 'Infrastructure' },
  { ticker: 'APOLLOHOSP', name: 'Apollo Hospitals', sector: 'Healthcare' },
  { ticker: 'ASIANPAINT', name: 'Asian Paints', sector: 'Consumer' },
  { ticker: 'AXISBANK', name: 'Axis Bank', sector: 'Banking' },
  { ticker: 'BAJAJ-AUTO', name: 'Bajaj Auto', sector: 'Auto' },
  { ticker: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'NBFC' },
  { ticker: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Financial Services' },
  { ticker: 'BPCL', name: 'BPCL', sector: 'Energy' },
  { ticker: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom' },
  { ticker: 'BRITANNIA', name: 'Britannia Industries', sector: 'FMCG' },
  { ticker: 'CIPLA', name: 'Cipla', sector: 'Pharma' },
  { ticker: 'COALINDIA', name: 'Coal India', sector: 'Mining' },
  { ticker: 'DIVISLAB', name: "Divi's Laboratories", sector: 'Pharma' },
  { ticker: 'DRREDDY', name: "Dr. Reddy's Laboratories", sector: 'Pharma' },
  { ticker: 'EICHERMOT', name: 'Eicher Motors', sector: 'Auto' },
  { ticker: 'GRASIM', name: 'Grasim Industries', sector: 'Diversified' },
  { ticker: 'HCLTECH', name: 'HCL Technologies', sector: 'IT' },
  { ticker: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking' },
  { ticker: 'HDFCLIFE', name: 'HDFC Life Insurance', sector: 'Insurance' },
  { ticker: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Auto' },
  { ticker: 'HINDALCO', name: 'Hindalco Industries', sector: 'Metals' },
  { ticker: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG' },
  { ticker: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking' },
  { ticker: 'ITC', name: 'ITC', sector: 'FMCG' },
  { ticker: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Banking' },
  { ticker: 'INFY', name: 'Infosys', sector: 'IT' },
  { ticker: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals' },
  { ticker: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking' },
  { ticker: 'LT', name: 'Larsen & Toubro', sector: 'Engineering' },
  { ticker: 'M&M', name: 'Mahindra & Mahindra', sector: 'Auto' },
  { ticker: 'MARUTI', name: 'Maruti Suzuki', sector: 'Auto' },
  { ticker: 'NESTLEIND', name: 'Nestle India', sector: 'FMCG' },
  { ticker: 'NTPC', name: 'NTPC', sector: 'Power' },
  { ticker: 'ONGC', name: 'ONGC', sector: 'Energy' },
  { ticker: 'POWERGRID', name: 'Power Grid Corporation', sector: 'Power' },
  { ticker: 'RELIANCE', name: 'Reliance Industries', sector: 'Diversified' },
  { ticker: 'SBILIFE', name: 'SBI Life Insurance', sector: 'Insurance' },
  { ticker: 'SBIN', name: 'State Bank of India', sector: 'Banking' },
  { ticker: 'SUNPHARMA', name: 'Sun Pharmaceutical', sector: 'Pharma' },
  { ticker: 'TCS', name: 'Tata Consultancy Services', sector: 'IT' },
  { ticker: 'TATACONSUM', name: 'Tata Consumer Products', sector: 'FMCG' },
  { ticker: 'TATAMOTORS', name: 'Tata Motors', sector: 'Auto' },
  { ticker: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals' },
  { ticker: 'TECHM', name: 'Tech Mahindra', sector: 'IT' },
  { ticker: 'TITAN', name: 'Titan Company', sector: 'Consumer' },
  { ticker: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Cement' },
  { ticker: 'UPL', name: 'UPL', sector: 'Agrochem' },
  { ticker: 'WIPRO', name: 'Wipro', sector: 'IT' },
  { ticker: 'ZOMATO', name: 'Zomato', sector: 'Consumer Tech' },
];

export const NIFTY_NEXT_50: StockInfo[] = [
  { ticker: 'ABB', name: 'ABB India', sector: 'Engineering' },
  { ticker: 'AMBUJACEM', name: 'Ambuja Cements', sector: 'Cement' },
  { ticker: 'AUROPHARMA', name: 'Aurobindo Pharma', sector: 'Pharma' },
  { ticker: 'BANKBARODA', name: 'Bank of Baroda', sector: 'Banking' },
  { ticker: 'BERGEPAINT', name: 'Berger Paints', sector: 'Consumer' },
  { ticker: 'BOSCHLTD', name: 'Bosch', sector: 'Auto Ancillary' },
  { ticker: 'CANBK', name: 'Canara Bank', sector: 'Banking' },
  { ticker: 'CHOLAFIN', name: 'Cholamandalam Investment', sector: 'NBFC' },
  { ticker: 'COLPAL', name: 'Colgate-Palmolive India', sector: 'FMCG' },
  { ticker: 'DABUR', name: 'Dabur India', sector: 'FMCG' },
  { ticker: 'DLF', name: 'DLF', sector: 'Real Estate' },
  { ticker: 'GODREJCP', name: 'Godrej Consumer Products', sector: 'FMCG' },
  { ticker: 'GUJGASLTD', name: 'Gujarat Gas', sector: 'Utilities' },
  { ticker: 'HAL', name: 'Hindustan Aeronautics', sector: 'Defence' },
  { ticker: 'HAVELLS', name: 'Havells India', sector: 'Consumer Electricals' },
  { ticker: 'ICICIGI', name: 'ICICI Lombard', sector: 'Insurance' },
  { ticker: 'ICICIPRULI', name: 'ICICI Prudential Life', sector: 'Insurance' },
  { ticker: 'INDIGO', name: 'IndiGo (InterGlobe Aviation)', sector: 'Aviation' },
  { ticker: 'INDUSTOWER', name: 'Indus Towers', sector: 'Telecom' },
  { ticker: 'IOC', name: 'Indian Oil Corporation', sector: 'Energy' },
  { ticker: 'IRCTC', name: 'IRCTC', sector: 'Travel & Tourism' },
  { ticker: 'LUPIN', name: 'Lupin', sector: 'Pharma' },
  { ticker: 'MCDOWELL-N', name: 'United Spirits', sector: 'FMCG' },
  { ticker: 'MPHASIS', name: 'Mphasis', sector: 'IT' },
  { ticker: 'NAUKRI', name: 'Info Edge (Naukri)', sector: 'Internet' },
  { ticker: 'PAGEIND', name: 'Page Industries', sector: 'Textiles' },
  { ticker: 'PERSISTENT', name: 'Persistent Systems', sector: 'IT' },
  { ticker: 'PIDILITIND', name: 'Pidilite Industries', sector: 'Chemicals' },
  { ticker: 'PIIND', name: 'PI Industries', sector: 'Agrochem' },
  { ticker: 'PNB', name: 'Punjab National Bank', sector: 'Banking' },
  { ticker: 'POLICYBZR', name: 'PB Fintech (PolicyBazaar)', sector: 'Fintech' },
  { ticker: 'RECLTD', name: 'REC', sector: 'NBFC' },
  { ticker: 'SAIL', name: 'Steel Authority of India', sector: 'Metals' },
  { ticker: 'SHREECEM', name: 'Shree Cement', sector: 'Cement' },
  { ticker: 'SIEMENS', name: 'Siemens India', sector: 'Engineering' },
  { ticker: 'TATAPOWER', name: 'Tata Power', sector: 'Power' },
  { ticker: 'TORNTPHARM', name: 'Torrent Pharmaceuticals', sector: 'Pharma' },
  { ticker: 'TRENT', name: 'Trent', sector: 'Retail' },
  { ticker: 'UNIONBANK', name: 'Union Bank of India', sector: 'Banking' },
  { ticker: 'VBL', name: 'Varun Beverages', sector: 'FMCG' },
  { ticker: 'VEDL', name: 'Vedanta', sector: 'Metals' },
  { ticker: 'VOLTAS', name: 'Voltas', sector: 'Consumer Electricals' },
  { ticker: 'WHIRLPOOL', name: 'Whirlpool of India', sector: 'Consumer Durables' },
  { ticker: 'YESBANK', name: 'Yes Bank', sector: 'Banking' },
  { ticker: 'ZYDUSLIFE', name: 'Zydus Lifesciences', sector: 'Pharma' },
];

export const NIFTY_MIDCAP_150: StockInfo[] = [
  { ticker: 'AARTIIND', name: 'Aarti Industries', sector: 'Chemicals' },
  { ticker: 'ABCAPITAL', name: 'Aditya Birla Capital', sector: 'Financial Services' },
  { ticker: 'ABFRL', name: 'Aditya Birla Fashion & Retail', sector: 'Retail' },
  { ticker: 'ALKEM', name: 'Alkem Laboratories', sector: 'Pharma' },
  { ticker: 'APLAPOLLO', name: 'APL Apollo Tubes', sector: 'Metals' },
  { ticker: 'APOLLOTYRE', name: 'Apollo Tyres', sector: 'Auto' },
  { ticker: 'ASTRAL', name: 'Astral', sector: 'Consumer' },
  { ticker: 'ATGL', name: 'Adani Total Gas', sector: 'Energy' },
  { ticker: 'BALKRISIND', name: 'Balkrishna Industries', sector: 'Auto' },
  { ticker: 'BATAINDIA', name: 'Bata India', sector: 'Consumer' },
  { ticker: 'BHARATFORG', name: 'Bharat Forge', sector: 'Engineering' },
  { ticker: 'BHEL', name: 'Bharat Heavy Electricals', sector: 'Engineering' },
  { ticker: 'BIOCON', name: 'Biocon', sector: 'Pharma' },
  { ticker: 'CGPOWER', name: 'CG Power & Industrial Solutions', sector: 'Engineering' },
  { ticker: 'COFORGE', name: 'Coforge', sector: 'IT' },
  { ticker: 'CONCOR', name: 'Container Corporation of India', sector: 'Logistics' },
  { ticker: 'CUMMINSIND', name: 'Cummins India', sector: 'Engineering' },
  { ticker: 'DALBHARAT', name: 'Dalmia Bharat', sector: 'Cement' },
  { ticker: 'DEEPAKNTR', name: 'Deepak Nitrite', sector: 'Chemicals' },
  { ticker: 'DIXON', name: 'Dixon Technologies', sector: 'Consumer Tech' },
  { ticker: 'EMAMILTD', name: 'Emami', sector: 'FMCG' },
  { ticker: 'FACT', name: 'Fertilisers & Chemicals Travancore', sector: 'Chemicals' },
  { ticker: 'FEDERALBNK', name: 'Federal Bank', sector: 'Banking' },
  { ticker: 'GLAND', name: 'Gland Pharma', sector: 'Pharma' },
  { ticker: 'GLAXO', name: 'GSK Pharmaceuticals', sector: 'Pharma' },
  { ticker: 'GMRINFRA', name: 'GMR Airports Infrastructure', sector: 'Infrastructure' },
  { ticker: 'GODREJIND', name: 'Godrej Industries', sector: 'Diversified' },
  { ticker: 'GODREJPROP', name: 'Godrej Properties', sector: 'Real Estate' },
  { ticker: 'GSPL', name: 'Gujarat State Petronet', sector: 'Energy' },
  { ticker: 'HINDPETRO', name: 'Hindustan Petroleum Corporation', sector: 'Energy' },
  { ticker: 'HONASA', name: 'Honasa Consumer (Mamaearth)', sector: 'FMCG' },
  { ticker: 'HUDCO', name: 'Housing & Urban Development Corporation', sector: 'NBFC' },
  { ticker: 'IDFCFIRSTB', name: 'IDFC First Bank', sector: 'Banking' },
  { ticker: 'IHCL', name: 'Indian Hotels Company', sector: 'Consumer' },
  { ticker: 'IGL', name: 'Indraprastha Gas', sector: 'Energy' },
  { ticker: 'INDIANB', name: 'Indian Bank', sector: 'Banking' },
  { ticker: 'INDHOTEL', name: 'Indian Hotels', sector: 'Consumer' },
  { ticker: 'IPCALAB', name: 'IPCA Laboratories', sector: 'Pharma' },
  { ticker: 'JKCEMENT', name: 'JK Cement', sector: 'Cement' },
  { ticker: 'JSWENERGY', name: 'JSW Energy', sector: 'Power' },
  { ticker: 'KALYANKJIL', name: 'Kalyan Jewellers', sector: 'Retail' },
  { ticker: 'KPITTECH', name: 'KPIT Technologies', sector: 'IT' },
  { ticker: 'LAURUSLABS', name: 'Laurus Labs', sector: 'Pharma' },
  { ticker: 'LICHSGFIN', name: 'LIC Housing Finance', sector: 'NBFC' },
  { ticker: 'LINDEINDIA', name: 'Linde India', sector: 'Chemicals' },
  { ticker: 'LTIM', name: 'LTIMindtree', sector: 'IT' },
  { ticker: 'LTTS', name: 'L&T Technology Services', sector: 'IT' },
  { ticker: 'MARICO', name: 'Marico', sector: 'FMCG' },
  { ticker: 'MAXHEALTH', name: 'Max Healthcare Institute', sector: 'Healthcare' },
  { ticker: 'MCX', name: 'Multi Commodity Exchange', sector: 'Capital Markets' },
  { ticker: 'MFSL', name: 'Max Financial Services', sector: 'Insurance' },
  { ticker: 'MOTHERSON', name: 'Samvardhana Motherson International', sector: 'Auto' },
  { ticker: 'MRF', name: 'MRF', sector: 'Auto' },
  { ticker: 'MUTHOOTFIN', name: 'Muthoot Finance', sector: 'NBFC' },
  { ticker: 'NMDC', name: 'NMDC', sector: 'Metals' },
  { ticker: 'OBEROIRLTY', name: 'Oberoi Realty', sector: 'Real Estate' },
  { ticker: 'OFSS', name: 'Oracle Financial Services Software', sector: 'IT' },
  { ticker: 'PATANJALI', name: 'Patanjali Foods', sector: 'FMCG' },
  { ticker: 'PETRONET', name: 'Petronet LNG', sector: 'Energy' },
  { ticker: 'PFC', name: 'Power Finance Corporation', sector: 'NBFC' },
  { ticker: 'PHOENIXLTD', name: 'Phoenix Mills', sector: 'Real Estate' },
  { ticker: 'PRESTIGE', name: 'Prestige Estates Projects', sector: 'Real Estate' },
  { ticker: 'RITES', name: 'RITES', sector: 'Infrastructure' },
  { ticker: 'SJVN', name: 'SJVN', sector: 'Power' },
  { ticker: 'SOLARINDS', name: 'Solar Industries India', sector: 'Defence' },
  { ticker: 'STARHEALTH', name: 'Star Health & Allied Insurance', sector: 'Insurance' },
  { ticker: 'SUNDARMFIN', name: 'Sundaram Finance', sector: 'NBFC' },
  { ticker: 'SUNTV', name: 'Sun TV Network', sector: 'Media' },
  { ticker: 'SUPREMEIND', name: 'Supreme Industries', sector: 'Consumer' },
  { ticker: 'SUZLON', name: 'Suzlon Energy', sector: 'Power' },
  { ticker: 'TATACOMM', name: 'Tata Communications', sector: 'Telecom' },
  { ticker: 'TATAELXSI', name: 'Tata Elxsi', sector: 'IT' },
  { ticker: 'TORNTPOWER', name: 'Torrent Power', sector: 'Power' },
  { ticker: 'TVSMOTOR', name: 'TVS Motor Company', sector: 'Auto' },
  { ticker: 'UBL', name: 'United Breweries', sector: 'FMCG' },
  { ticker: 'VARUNBEV', name: 'Varun Beverages', sector: 'FMCG' },
  { ticker: 'ZEEL', name: 'Zee Entertainment Enterprises', sector: 'Media' },
  { ticker: 'ACC', name: 'ACC', sector: 'Cement' },
  { ticker: 'ADANIGREEN', name: 'Adani Green Energy', sector: 'Power' },
  { ticker: 'ADANIPOWER', name: 'Adani Power', sector: 'Power' },
  { ticker: 'AIAENG', name: 'AIA Engineering', sector: 'Engineering' },
  { ticker: 'AJANTPHARM', name: 'Ajanta Pharma', sector: 'Pharma' },
  { ticker: 'AKZOINDIA', name: 'Akzo Nobel India', sector: 'Chemicals' },
  { ticker: 'APARINDS', name: 'Apar Industries', sector: 'Engineering' },
  { ticker: 'ASHOKLEY', name: 'Ashok Leyland', sector: 'Auto' },
  { ticker: 'ASIANHOTNR', name: 'Asian Hotels (North)', sector: 'Consumer' },
  { ticker: 'AUBANK', name: 'AU Small Finance Bank', sector: 'Banking' },
  { ticker: 'BANDHANBNK', name: 'Bandhan Bank', sector: 'Banking' },
  { ticker: 'BANKINDIA', name: 'Bank of India', sector: 'Banking' },
  { ticker: 'BLUEDART', name: 'Blue Dart Express', sector: 'Logistics' },
  { ticker: 'CASTROLIND', name: 'Castrol India', sector: 'Energy' },
  { ticker: 'CENTRALBK', name: 'Central Bank of India', sector: 'Banking' },
  { ticker: 'CHAMBLFERT', name: 'Chambal Fertilisers', sector: 'Chemicals' },
  { ticker: 'CHALET', name: 'Chalet Hotels', sector: 'Consumer' },
  { ticker: 'CROMPTON', name: 'Crompton Greaves Consumer Electricals', sector: 'Consumer' },
  { ticker: 'CESC', name: 'CESC', sector: 'Power' },
  { ticker: 'CYIENT', name: 'Cyient', sector: 'IT' },
  { ticker: 'EIHOTEL', name: 'EIH (Oberoi Hotels)', sector: 'Consumer' },
  { ticker: 'ELGIEQUIP', name: 'Elgi Equipments', sector: 'Engineering' },
  { ticker: 'ENDURANCE', name: 'Endurance Technologies', sector: 'Auto' },
  { ticker: 'ENGINERSIN', name: 'Engineers India', sector: 'Engineering' },
  { ticker: 'ESCORTS', name: 'Escorts Kubota', sector: 'Auto' },
  { ticker: 'EXIDEIND', name: 'Exide Industries', sector: 'Auto' },
  { ticker: 'FORTIS', name: 'Fortis Healthcare', sector: 'Healthcare' },
  { ticker: 'GAIL', name: 'GAIL India', sector: 'Energy' },
  { ticker: 'GLENMARK', name: 'Glenmark Pharmaceuticals', sector: 'Pharma' },
  { ticker: 'GNFC', name: 'Gujarat Narmada Valley Fertilizers', sector: 'Chemicals' },
  { ticker: 'GPPL', name: 'Gujarat Pipavav Port', sector: 'Infrastructure' },
  { ticker: 'GRAPHITE', name: 'Graphite India', sector: 'Metals' },
  { ticker: 'GSFC', name: 'Gujarat State Fertilizers & Chemicals', sector: 'Chemicals' },
  { ticker: 'HFCL', name: 'HFCL', sector: 'Telecom' },
  { ticker: 'HINDZINC', name: 'Hindustan Zinc', sector: 'Metals' },
  { ticker: 'IDBI', name: 'IDBI Bank', sector: 'Banking' },
  { ticker: 'IRCON', name: 'IRCON International', sector: 'Infrastructure' },
  { ticker: 'JBCHEPHARM', name: 'JB Chemicals & Pharmaceuticals', sector: 'Pharma' },
  { ticker: 'JKLAKSHMI', name: 'JK Lakshmi Cement', sector: 'Cement' },
  { ticker: 'JPPOWER', name: 'Jaiprakash Power Ventures', sector: 'Power' },
  { ticker: 'JSPL', name: 'Jindal Steel & Power', sector: 'Metals' },
  { ticker: 'JUBLFOOD', name: 'Jubilant FoodWorks', sector: 'Consumer' },
  { ticker: 'JUSTDIAL', name: 'Just Dial', sector: 'Consumer Tech' },
  { ticker: 'KAJARIACER', name: 'Kajaria Ceramics', sector: 'Consumer' },
  { ticker: 'KANSAINER', name: 'Kansai Nerolac Paints', sector: 'Consumer' },
  { ticker: 'KEC', name: 'KEC International', sector: 'Engineering' },
  { ticker: 'KFINTECH', name: 'KFin Technologies', sector: 'Financial Services' },
  { ticker: 'LALPATHLAB', name: 'Dr Lal PathLabs', sector: 'Healthcare' },
  { ticker: 'LICI', name: 'Life Insurance Corporation of India', sector: 'Insurance' },
  { ticker: 'MAHABANK', name: 'Bank of Maharashtra', sector: 'Banking' },
  { ticker: 'MAHINDCIE', name: 'Mahindra CIE Automotive', sector: 'Auto' },
  { ticker: 'MANAPPURAM', name: 'Manappuram Finance', sector: 'NBFC' },
  { ticker: 'MASFIN', name: 'MAS Financial Services', sector: 'NBFC' },
  { ticker: 'MEDANTA', name: 'Global Health (Medanta)', sector: 'Healthcare' },
  { ticker: 'NATCOPHARM', name: 'Natco Pharma', sector: 'Pharma' },
  { ticker: 'NAVINFLUOR', name: 'Navin Fluorine International', sector: 'Chemicals' },
  { ticker: 'NIACL', name: 'New India Assurance', sector: 'Insurance' },
  { ticker: 'NLC', name: 'NLC India', sector: 'Power' },
  { ticker: 'OLECTRA', name: 'Olectra Greentech', sector: 'Auto' },
  { ticker: 'PCBL', name: 'PCBL', sector: 'Chemicals' },
  { ticker: 'PGHH', name: 'Procter & Gamble Hygiene & Health Care', sector: 'FMCG' },
  { ticker: 'PNBHOUSING', name: 'PNB Housing Finance', sector: 'NBFC' },
  { ticker: 'POLYMED', name: 'Poly Medicure', sector: 'Healthcare' },
  { ticker: 'POWERMECH', name: 'Power Mech Projects', sector: 'Engineering' },
  { ticker: 'RAMCOCEM', name: 'Ramco Cements', sector: 'Cement' },
  { ticker: 'RELAXO', name: 'Relaxo Footwears', sector: 'Consumer' },
  { ticker: 'RPOWER', name: 'Reliance Power', sector: 'Power' },
  { ticker: 'SANOFI', name: 'Sanofi India', sector: 'Pharma' },
  { ticker: 'SCHAEFFLER', name: 'Schaeffler India', sector: 'Auto' },
  { ticker: 'SCI', name: 'Shipping Corporation of India', sector: 'Logistics' },
  { ticker: 'SKFINDIA', name: 'SKF India', sector: 'Engineering' },
  { ticker: 'SOBHA', name: 'Sobha', sector: 'Real Estate' },
  { ticker: 'SUNTECK', name: 'Sunteck Realty', sector: 'Real Estate' },
  { ticker: 'SUPRAJIT', name: 'Suprajit Engineering', sector: 'Auto' },
  { ticker: 'SUVENPHAR', name: 'Suven Pharmaceuticals', sector: 'Pharma' },
  { ticker: 'SYMPHONY', name: 'Symphony', sector: 'Consumer' },
  { ticker: 'TANLA', name: 'Tanla Platforms', sector: 'IT' },
  { ticker: 'THERMAX', name: 'Thermax', sector: 'Engineering' },
  { ticker: 'TIMKEN', name: 'Timken India', sector: 'Engineering' },
  { ticker: 'TINPLATE', name: 'Tinplate Company of India', sector: 'Metals' },
  { ticker: 'TTKPRESTIG', name: 'TTK Prestige', sector: 'Consumer' },
  { ticker: 'TVSHLTD', name: 'TVS Holdings', sector: 'Diversified' },
  { ticker: 'UCOBANK', name: 'UCO Bank', sector: 'Banking' },
];

export const NIFTY_SMALLCAP_250: StockInfo[] = [
  { ticker: 'AFFLE', name: 'Affle India', sector: 'Consumer Tech' },
  { ticker: 'AMBER', name: 'Amber Enterprises India', sector: 'Consumer' },
  { ticker: 'ANGELONE', name: 'Angel One', sector: 'Capital Markets' },
  { ticker: 'APTUS', name: 'Aptus Value Housing Finance', sector: 'NBFC' },
  { ticker: 'BALRAMCHIN', name: 'Balrampur Chini Mills', sector: 'FMCG' },
  { ticker: 'BIRLASOFT', name: 'Birlasoft', sector: 'IT' },
  { ticker: 'BSOFT', name: 'BEML Software', sector: 'IT' },
  { ticker: 'CAMPUS', name: 'Campus Activewear', sector: 'Consumer' },
  { ticker: 'CDSL', name: 'Central Depository Services (India)', sector: 'Capital Markets' },
  { ticker: 'CMSINFO', name: 'CMS Info Systems', sector: 'Financial Services' },
  { ticker: 'DELHIVERY', name: 'Delhivery', sector: 'Logistics' },
  { ticker: 'DEVYANI', name: 'Devyani International', sector: 'Consumer' },
  { ticker: 'EQUITASBNK', name: 'Equitas Small Finance Bank', sector: 'Banking' },
  { ticker: 'ERIS', name: 'Eris Lifesciences', sector: 'Pharma' },
  { ticker: 'EXIDE', name: 'Exide Industries', sector: 'Auto' },
  { ticker: 'FIVESTAR', name: 'Five-Star Business Finance', sector: 'NBFC' },
  { ticker: 'FUSION', name: 'Fusion Micro Finance', sector: 'NBFC' },
  { ticker: 'GPIL', name: 'Godawari Power & Ispat', sector: 'Metals' },
  { ticker: 'GRSE', name: 'Garden Reach Shipbuilders & Engineers', sector: 'Defence' },
  { ticker: 'HOMEFIRST', name: 'Home First Finance Company', sector: 'NBFC' },
  { ticker: 'IREDA', name: 'Indian Renewable Energy Development Agency', sector: 'NBFC' },
  { ticker: 'JMFINANCL', name: 'JM Financial', sector: 'Capital Markets' },
  { ticker: 'KAJARIA', name: 'Kajaria Ceramics', sector: 'Consumer' },
  { ticker: 'KIRLOSENG', name: 'Kirloskar Electric Company', sector: 'Engineering' },
  { ticker: 'MEDPLUS', name: 'MedPlus Health Services', sector: 'Retail' },
  { ticker: 'MIDHANI', name: 'Mishra Dhatu Nigam', sector: 'Defence' },
  { ticker: 'MTAR', name: 'MTAR Technologies', sector: 'Defence' },
  { ticker: 'NATCO', name: 'Natco Pharma', sector: 'Pharma' },
  { ticker: 'NCC', name: 'NCC', sector: 'Infrastructure' },
  { ticker: 'NEULANDLAB', name: 'Neuland Laboratories', sector: 'Pharma' },
  { ticker: 'NH', name: 'Narayana Hrudayalaya', sector: 'Healthcare' },
  { ticker: 'NUVOCO', name: 'Nuvoco Vistas Corporation', sector: 'Cement' },
  { ticker: 'PARADEEP', name: 'Paradeep Phosphates', sector: 'Chemicals' },
  { ticker: 'PAYTM', name: 'One97 Communications (Paytm)', sector: 'Consumer Tech' },
  { ticker: 'RAILTEL', name: 'RailTel Corporation of India', sector: 'Telecom' },
  { ticker: 'RATNAMANI', name: 'Ratnamani Metals & Tubes', sector: 'Metals' },
  { ticker: 'REDINGTON', name: 'Redington', sector: 'IT' },
  { ticker: 'RVNL', name: 'Rail Vikas Nigam', sector: 'Infrastructure' },
  { ticker: 'SAFARI', name: 'Safari Industries India', sector: 'Consumer' },
  { ticker: 'SBICARD', name: 'SBI Cards & Payment Services', sector: 'Financial Services' },
  { ticker: 'SHOPERSTOP', name: 'Shoppers Stop', sector: 'Retail' },
  { ticker: 'STLTECH', name: 'Sterlite Technologies', sector: 'Telecom' },
  { ticker: 'SUDARSCHEM', name: 'Sudarshan Chemical Industries', sector: 'Chemicals' },
  { ticker: 'SUMICHEM', name: 'Sumitomo Chemical India', sector: 'Agrochem' },
  { ticker: 'SURYAROSNI', name: 'Surya Roshni', sector: 'Consumer' },
  { ticker: 'TEAMLEASE', name: 'TeamLease Services', sector: 'Consumer' },
  { ticker: 'TITAGARH', name: 'Titagarh Rail Systems', sector: 'Engineering' },
  { ticker: 'UJJIVANSFB', name: 'Ujjivan Small Finance Bank', sector: 'Banking' },
  { ticker: 'VGUARD', name: 'V-Guard Industries', sector: 'Consumer' },
  { ticker: 'WABCOINDIA', name: 'Wabtec India (Knorr-Bremse)', sector: 'Engineering' },
  { ticker: 'AAVAS', name: 'Aavas Financiers', sector: 'NBFC' },
  { ticker: 'ABSLBANETF', name: 'Aditya Birla Sun Life Nifty Bank ETF', sector: 'Capital Markets' },
  { ticker: 'ACE', name: 'Action Construction Equipment', sector: 'Engineering' },
  { ticker: 'AGIIL', name: 'AGI Infra', sector: 'Real Estate' },
  { ticker: 'AHLUCONT', name: 'Ahluwalia Contracts India', sector: 'Infrastructure' },
  { ticker: 'AJMERA', name: 'Ajmera Realty & Infra India', sector: 'Real Estate' },
  { ticker: 'ALEMBICLTD', name: 'Alembic', sector: 'Pharma' },
  { ticker: 'ALOKINDS', name: 'Alok Industries', sector: 'Textiles' },
  { ticker: 'AMARAJABAT', name: 'Amara Raja Energy & Mobility', sector: 'Auto' },
  { ticker: 'AMDIND', name: 'AMD Industries', sector: 'Consumer' },
  { ticker: 'ANANTRAJ', name: 'Anant Raj', sector: 'Real Estate' },
  { ticker: 'ANURAS', name: 'Anupam Rasayan India', sector: 'Chemicals' },
  { ticker: 'APCOTEX', name: 'Apcotex Industries', sector: 'Chemicals' },
  { ticker: 'ARVINDFASN', name: 'Arvind Fashions', sector: 'Retail' },
  { ticker: 'ASAHI', name: 'Asahi India Glass', sector: 'Consumer' },
  { ticker: 'ASHIANA', name: 'Ashiana Housing', sector: 'Real Estate' },
  { ticker: 'ASKAUTOLTD', name: 'ASK Automotive', sector: 'Auto' },
  { ticker: 'ASTERDM', name: 'Aster DM Healthcare', sector: 'Healthcare' },
  { ticker: 'AVANTIFEED', name: 'Avanti Feeds', sector: 'FMCG' },
  { ticker: 'BAJAJELEC', name: 'Bajaj Electricals', sector: 'Consumer' },
  { ticker: 'BAJAJHFL', name: 'Bajaj Housing Finance', sector: 'NBFC' },
  { ticker: 'BALMLAWRIE', name: 'Balmer Lawrie & Co', sector: 'Diversified' },
  { ticker: 'BANSALWIRE', name: 'Bansal Wire Industries', sector: 'Metals' },
  { ticker: 'BASF', name: 'BASF India', sector: 'Chemicals' },
  { ticker: 'BECTORFOOD', name: "Mrs. Bectors Food Specialities", sector: 'FMCG' },
  { ticker: 'BFUTILITIE', name: 'BF Utilities', sector: 'Diversified' },
  { ticker: 'BIGBLOC', name: 'Bigbloc Construction', sector: 'Infrastructure' },
  { ticker: 'BLKASHYAP', name: 'B.L. Kashyap & Sons', sector: 'Infrastructure' },
  { ticker: 'BLS', name: 'BLS International Services', sector: 'Consumer' },
  { ticker: 'BOROLTD', name: 'Borosil', sector: 'Consumer' },
  { ticker: 'BRIGADE', name: 'Brigade Enterprises', sector: 'Real Estate' },
  { ticker: 'BSE', name: 'BSE', sector: 'Capital Markets' },
  { ticker: 'BVCL', name: 'Barak Valley Cements', sector: 'Cement' },
  { ticker: 'CAMLINFINE', name: 'Camlin Fine Sciences', sector: 'Chemicals' },
  { ticker: 'CAPACITE', name: 'Capacit\'e Infraprojects', sector: 'Infrastructure' },
  { ticker: 'CAPLIPOINT', name: 'Caplin Point Laboratories', sector: 'Pharma' },
  { ticker: 'CARBORUNIV', name: 'Carborundum Universal', sector: 'Engineering' },
  { ticker: 'CARERATING', name: 'CARE Ratings', sector: 'Financial Services' },
  { ticker: 'CEATLTD', name: 'CEAT', sector: 'Auto' },
  { ticker: 'CENTURYTEX', name: 'Century Textiles & Industries', sector: 'Textiles' },
  { ticker: 'CENTURYPLY', name: 'Century Plyboards India', sector: 'Consumer' },
  { ticker: 'CERA', name: 'Cera Sanitaryware', sector: 'Consumer' },
  { ticker: 'CHEMPLASTS', name: 'Chemplast Sanmar', sector: 'Chemicals' },
  { ticker: 'CHOLAHLDNG', name: 'Cholamandalam Financial Holdings', sector: 'Financial Services' },
  { ticker: 'CLEAN', name: 'Clean Science & Technology', sector: 'Chemicals' },
  { ticker: 'COCHINSHIP', name: 'Cochin Shipyard', sector: 'Defence' },
  { ticker: 'CONFIPET', name: 'Confidence Petroleum India', sector: 'Energy' },
  { ticker: 'CRAFTSMAN', name: 'Craftsman Automation', sector: 'Engineering' },
  { ticker: 'CRISIL', name: 'CRISIL', sector: 'Financial Services' },
  { ticker: 'CSBBANK', name: 'CSB Bank', sector: 'Banking' },
  { ticker: 'DCB', name: 'DCB Bank', sector: 'Banking' },
  { ticker: 'DFMFOODS', name: 'DFM Foods', sector: 'FMCG' },
  { ticker: 'DHANI', name: 'Dhani Services', sector: 'Financial Services' },
  { ticker: 'DHARMAJ', name: 'Dharmaj Crop Guard', sector: 'Agrochem' },
  { ticker: 'DHUNSERI', name: 'Dhunseri Ventures', sector: 'Diversified' },
  { ticker: 'DOMS', name: 'DOMS Industries', sector: 'Consumer' },
  { ticker: 'DREAMFOLKS', name: 'Dreamfolks Services', sector: 'Consumer' },
  { ticker: 'DYCL', name: 'Dynamic Cables', sector: 'Engineering' },
  { ticker: 'EASEMYTRIP', name: 'Easy Trip Planners', sector: 'Consumer Tech' },
  { ticker: 'EIDPARRY', name: 'EID Parry (India)', sector: 'FMCG' },
  { ticker: 'ELECTCAST', name: 'Electrosteel Castings', sector: 'Metals' },
  { ticker: 'EMKAY', name: 'Emkay Global Financial Services', sector: 'Capital Markets' },
  { ticker: 'ENPRO', name: 'Enpro Systems', sector: 'Engineering' },
  { ticker: 'EPL', name: 'EPL', sector: 'Consumer' },
  { ticker: 'ESABINDIA', name: 'ESAB India', sector: 'Engineering' },
  { ticker: 'ESTER', name: 'Ester Industries', sector: 'Chemicals' },
  { ticker: 'ETHOSLTD', name: 'Ethos', sector: 'Retail' },
  { ticker: 'EVONIK', name: 'Evonik India', sector: 'Chemicals' },
  { ticker: 'FINEORG', name: 'Fine Organic Industries', sector: 'Chemicals' },
  { ticker: 'FILATEX', name: 'Filatex India', sector: 'Textiles' },
  { ticker: 'FINPIPE', name: 'Finolex Industries', sector: 'Consumer' },
  { ticker: 'FLUOROCHEM', name: 'Gujarat Fluorochemicals', sector: 'Chemicals' },
  { ticker: 'FMGOETZE', name: 'Federal-Mogul Goetze India', sector: 'Auto' },
  { ticker: 'FOODWORKS', name: 'Jubilant Foodworks', sector: 'Consumer' },
  { ticker: 'GABRIEL', name: 'Gabriel India', sector: 'Auto' },
  { ticker: 'GANDHAR', name: 'Gandhar Oil Refinery', sector: 'Energy' },
  { ticker: 'GARFIBRES', name: 'Garware Technical Fibres', sector: 'Textiles' },
  { ticker: 'GATEWAY', name: 'Gateway Distriparks', sector: 'Logistics' },
  { ticker: 'GICRE', name: 'General Insurance Corporation of India', sector: 'Insurance' },
  { ticker: 'GMDCLTD', name: 'Gujarat Mineral Development Corporation', sector: 'Metals' },
  { ticker: 'GODFRYPHLP', name: 'Godfrey Phillips India', sector: 'FMCG' },
  { ticker: 'GODHA', name: 'Godha Cabcon & Insulation', sector: 'Engineering' },
  { ticker: 'GRANULES', name: 'Granules India', sector: 'Pharma' },
  { ticker: 'GREENPANEL', name: 'Greenpanel Industries', sector: 'Consumer' },
  { ticker: 'GRINDWELL', name: 'Grindwell Norton', sector: 'Engineering' },
  { ticker: 'GTPL', name: 'GTPL Hathway', sector: 'Media' },
  { ticker: 'GUJALKALI', name: 'Gujarat Alkalies & Chemicals', sector: 'Chemicals' },
  { ticker: 'HAPPSTMNDS', name: 'Happiest Minds Technologies', sector: 'IT' },
  { ticker: 'HARSHA', name: 'Harsha Engineers International', sector: 'Engineering' },
  { ticker: 'HAWKINCOOK', name: 'Hawkins Cookers', sector: 'Consumer' },
  { ticker: 'HECPROJECT', name: 'HEC Infra Projects', sector: 'Infrastructure' },
  { ticker: 'HIMATSEIDE', name: 'Himatsingka Seide', sector: 'Textiles' },
  { ticker: 'HINDCOPPER', name: 'Hindustan Copper', sector: 'Metals' },
  { ticker: 'HINDWAREHO', name: 'Hindware Home Innovation', sector: 'Consumer' },
  { ticker: 'HONEYWELL', name: 'Honeywell Automation India', sector: 'Engineering' },
  { ticker: 'HSCL', name: 'Himadri Speciality Chemical', sector: 'Chemicals' },
  { ticker: 'ICRA', name: 'ICRA', sector: 'Financial Services' },
  { ticker: 'IGPL', name: 'IG Petrochemicals', sector: 'Chemicals' },
  { ticker: 'IGSIL', name: 'IGS Industries', sector: 'Consumer' },
  { ticker: 'IMAGICAA', name: 'Imagicaaworld Entertainment', sector: 'Consumer' },
  { ticker: 'INDIAGLYCO', name: 'India Glycols', sector: 'Chemicals' },
  { ticker: 'INDIAMART', name: 'IndiaMart InterMesh', sector: 'Consumer Tech' },
  { ticker: 'INNOVACAP', name: 'Innova Captab', sector: 'Pharma' },
  { ticker: 'INSECTICID', name: 'Insecticides India', sector: 'Agrochem' },
  { ticker: 'INTELLECT', name: 'Intellect Design Arena', sector: 'IT' },
  { ticker: 'IOLCP', name: 'IOL Chemicals & Pharmaceuticals', sector: 'Pharma' },
  { ticker: 'IRB', name: 'IRB Infrastructure Developers', sector: 'Infrastructure' },
  { ticker: 'ISEC', name: 'ICICI Securities', sector: 'Capital Markets' },
  { ticker: 'ITDC', name: 'India Tourism Development Corporation', sector: 'Consumer' },
  { ticker: 'IVRCL', name: 'IVRCL', sector: 'Infrastructure' },
  { ticker: 'IWL', name: 'Inox Wind', sector: 'Power' },
  { ticker: 'JAMNAAUTO', name: 'Jamna Auto Industries', sector: 'Auto' },
  { ticker: 'JAYAGROGN', name: 'Jayagro Genetics', sector: 'Agrochem' },
  { ticker: 'JBMA', name: 'JBM Auto', sector: 'Auto' },
  { ticker: 'JHS', name: 'JHS Svendgaard Laboratories', sector: 'FMCG' },
  { ticker: 'JINDALSAW', name: 'Jindal Saw', sector: 'Metals' },
  { ticker: 'JINDALPOLY', name: 'Jindal Poly Films', sector: 'Chemicals' },
  { ticker: 'JKIL', name: 'J Kumar Infraprojects', sector: 'Infrastructure' },
  { ticker: 'JKTYRE', name: 'JK Tyre & Industries', sector: 'Auto' },
  { ticker: 'JOSHUAPH', name: 'Joshua Pharmaceuticals', sector: 'Pharma' },
  { ticker: 'JUBLINGREA', name: 'Jubilant Ingrevia', sector: 'Chemicals' },
  { ticker: 'KALPATPOWR', name: 'Kalpataru Projects International', sector: 'Engineering' },
  { ticker: 'KANPRPLAS', name: 'Kanpur Plastipack', sector: 'Consumer' },
  { ticker: 'KARBICOLIN', name: 'Karbi Colin', sector: 'Chemicals' },
  { ticker: 'KARUR', name: 'Karur Vysya Bank', sector: 'Banking' },
  { ticker: 'KENNAMET', name: 'Kennametal India', sector: 'Engineering' },
  { ticker: 'KHADIM', name: 'Khadim India', sector: 'Consumer' },
  { ticker: 'KIRIINDUS', name: 'Kiri Industries', sector: 'Chemicals' },
  { ticker: 'KITEX', name: 'Kitex Garments', sector: 'Textiles' },
  { ticker: 'KNRCON', name: 'KNR Constructions', sector: 'Infrastructure' },
  { ticker: 'KOPRAN', name: 'Kopran', sector: 'Pharma' },
  { ticker: 'KRBL', name: 'KRBL', sector: 'FMCG' },
  { ticker: 'KREBSBIO', name: 'Krebs Biochemicals', sector: 'Pharma' },
  { ticker: 'KSCL', name: 'Kaveri Seed Company', sector: 'Agrochem' },
  { ticker: 'LAKSHVILAS', name: 'Lakshmi Vilas Bank', sector: 'Banking' },
  { ticker: 'LATENTVIEW', name: 'Latent View Analytics', sector: 'IT' },
  { ticker: 'LEMONTREE', name: 'Lemon Tree Hotels', sector: 'Consumer' },
  { ticker: 'LLOYDSENGG', name: 'Lloyds Engineering Works', sector: 'Engineering' },
  { ticker: 'LSIL', name: 'Lotus Surgical Pharma', sector: 'Healthcare' },
  { ticker: 'LUXIND', name: 'Lux Industries', sector: 'Textiles' },
  { ticker: 'MAHARASHTRA', name: 'Maharashtra Scooters', sector: 'Auto' },
  { ticker: 'MAHASTEEL', name: 'Maharashtra Seamless', sector: 'Metals' },
  { ticker: 'MAHINDRA', name: 'Mahindra Holidays & Resorts', sector: 'Consumer' },
  { ticker: 'MAITHANALL', name: 'Maithan Alloys', sector: 'Metals' },
  { ticker: 'MANKIND', name: 'Mankind Pharma', sector: 'Pharma' },
  { ticker: 'MANGLMCEM', name: 'Mangalam Cement', sector: 'Cement' },
  { ticker: 'MANYAVAR', name: 'Vedant Fashions (Manyavar)', sector: 'Retail' },
  { ticker: 'MAPMYINDIA', name: 'CE Info Systems (MapMyIndia)', sector: 'Consumer Tech' },
  { ticker: 'MAXESTATES', name: 'Max Estates', sector: 'Real Estate' },
  { ticker: 'MCLEODRUS', name: 'McLeod Russel India', sector: 'FMCG' },
  { ticker: 'METROPOLIS', name: 'Metropolis Healthcare', sector: 'Healthcare' },
  { ticker: 'MMTC', name: 'MMTC', sector: 'Diversified' },
  { ticker: 'MOIL', name: 'MOIL', sector: 'Metals' },
  { ticker: 'MOREPENLAB', name: 'Morepen Laboratories', sector: 'Pharma' },
  { ticker: 'MOTILALOFS', name: 'Motilal Oswal Financial Services', sector: 'Capital Markets' },
  { ticker: 'MRPL', name: 'MRPL', sector: 'Energy' },
  { ticker: 'MUTHOOTCAP', name: 'Muthoot Capital Services', sector: 'NBFC' },
  { ticker: 'NAVA', name: 'NAVA', sector: 'Metals' },
  { ticker: 'NBCC', name: 'NBCC (India)', sector: 'Real Estate' },
  { ticker: 'NFL', name: 'National Fertilizers', sector: 'Chemicals' },
  { ticker: 'NIITLTD', name: 'NIIT', sector: 'Consumer Tech' },
  { ticker: 'NILKAMAL', name: 'Nilkamal', sector: 'Consumer' },
  { ticker: 'NIPTECHIN', name: 'NIP Technologies India', sector: 'IT' },
  { ticker: 'NKIND', name: 'Nuvama Wealth Management', sector: 'Capital Markets' },
  { ticker: 'NSKFIN', name: 'NSK Finance', sector: 'NBFC' },
  { ticker: 'NUCLEUS', name: 'Nucleus Software Exports', sector: 'IT' },
  { ticker: 'ONEPOINT', name: 'One Point One Solutions', sector: 'IT' },
  { ticker: 'ORIENTELEC', name: 'Orient Electric', sector: 'Consumer' },
  { ticker: 'ORIENTPAPER', name: 'Orient Paper & Industries', sector: 'Consumer' },
  { ticker: 'ORTINGLOB', name: 'Ortin Global', sector: 'Pharma' },
  { ticker: 'PANACEABIO', name: 'Panacea Biotec', sector: 'Pharma' },
  { ticker: 'PARAGMILK', name: 'Parag Milk Foods', sector: 'FMCG' },
  { ticker: 'PDSL', name: 'PDS', sector: 'Textiles' },
  { ticker: 'PENIND', name: 'Pen India', sector: 'Engineering' },
  { ticker: 'PIRAMALPH', name: 'Piramal Pharma', sector: 'Pharma' },
  { ticker: 'PLASTIBLEN', name: 'Plastiblends India', sector: 'Chemicals' },
  { ticker: 'POKARNA', name: 'Pokarna', sector: 'Consumer' },
  { ticker: 'POLYMATECH', name: 'Polymatech Electronics', sector: 'Engineering' },
  { ticker: 'POONAWALLA', name: 'Poonawalla Fincorp', sector: 'NBFC' },
  { ticker: 'PPAP', name: 'PPAP Automotive', sector: 'Auto' },
  { ticker: 'PRECWIRE', name: 'Precision Wires India', sector: 'Engineering' },
  { ticker: 'PRICOLLTD', name: 'Pricol', sector: 'Auto' },
  { ticker: 'PRINCEPIPE', name: 'Prince Pipes & Fittings', sector: 'Consumer' },
  { ticker: 'PURVA', name: 'Puravankara', sector: 'Real Estate' },
  { ticker: 'PVRINOX', name: 'PVR INOX', sector: 'Media' },
  { ticker: 'RACLGEAR', name: 'RACL Geartech', sector: 'Auto' },
  { ticker: 'RAINBOW', name: 'Rainbow Childrens Medicare', sector: 'Healthcare' },
  { ticker: 'RATEGAIN', name: 'RateGain Travel Technologies', sector: 'Consumer Tech' },
  { ticker: 'RBA', name: 'Restaurant Brands Asia', sector: 'Consumer' },
  { ticker: 'RESPONIND', name: 'Responsive Industries', sector: 'Consumer' },
  { ticker: 'RHFL', name: 'Reliance Home Finance', sector: 'NBFC' },
  { ticker: 'RKFORGE', name: 'RK Forgings', sector: 'Engineering' },
  { ticker: 'ROLCON', name: 'Rolcon Engineering', sector: 'Engineering' },
  { ticker: 'ROUTE', name: 'Route Mobile', sector: 'IT' },
  { ticker: 'RPGLIFE', name: 'RPG Life Sciences', sector: 'Pharma' },
  { ticker: 'RPTECH', name: 'Rashi Peripherals', sector: 'IT' },
  { ticker: 'SAGCEM', name: 'Sagar Cements', sector: 'Cement' },
  { ticker: 'SALSTEEL', name: 'SAL Steel', sector: 'Metals' },
  { ticker: 'SANDHAR', name: 'Sandhar Technologies', sector: 'Auto' },
  { ticker: 'SAPPHIRE', name: 'Sapphire Foods India', sector: 'Consumer' },
  { ticker: 'SAREGAMA', name: 'Saregama India', sector: 'Media' },
  { ticker: 'SBCL', name: 'Shivalik Bimetal Controls', sector: 'Engineering' },
  { ticker: 'SEPC', name: 'SEPC', sector: 'Infrastructure' },
  { ticker: 'SEQUENT', name: 'SeQuent Scientific', sector: 'Pharma' },
  { ticker: 'SHAREINDIA', name: 'Share India Securities', sector: 'Capital Markets' },
  { ticker: 'SHYAMMETL', name: 'Shyam Metalics & Energy', sector: 'Metals' },
  { ticker: 'SIGACHI', name: 'Sigachi Industries', sector: 'Chemicals' },
  { ticker: 'SIGNATURE', name: 'Signature Global India', sector: 'Real Estate' },
  { ticker: 'SMLISUZU', name: 'SML Isuzu', sector: 'Auto' },
  { ticker: 'SNOWMAN', name: 'Snowman Logistics', sector: 'Logistics' },
  { ticker: 'SOLARA', name: 'Solara Active Pharma Sciences', sector: 'Pharma' },
  { ticker: 'SOUTHWEST', name: 'Southwest Pinnacle Exploration', sector: 'Energy' },
  { ticker: 'SPANDANA', name: 'Spandana Sphoorty Financial', sector: 'NBFC' },
  { ticker: 'SPARC', name: 'Sun Pharma Advanced Research Company', sector: 'Pharma' },
  { ticker: 'SPENCERS', name: "Spencer's Retail", sector: 'Retail' },
  { ticker: 'SSWL', name: 'Steel Strips Wheels', sector: 'Auto' },
  { ticker: 'SUBEXLTD', name: 'Subex', sector: 'IT' },
  { ticker: 'SUPRIYA', name: 'Supriya Lifescience', sector: 'Pharma' },
  { ticker: 'SURAJ', name: 'Suraj Estate Developers', sector: 'Real Estate' },
  { ticker: 'SWSOLAR', name: 'Sterling and Wilson Renewable Energy', sector: 'Power' },
  { ticker: 'TANLAPLATF', name: 'Tanla Platforms', sector: 'IT' },
  { ticker: 'TATAINVEST', name: 'Tata Investment Corporation', sector: 'Financial Services' },
  { ticker: 'TEJASNET', name: 'Tejas Networks', sector: 'Telecom' },
  { ticker: 'TEXINFRA', name: 'Texmo Pipes & Products', sector: 'Engineering' },
  { ticker: 'THANGAMAL', name: 'Thangamayil Jewellery', sector: 'Retail' },
  { ticker: 'THYROCARE', name: 'Thyrocare Technologies', sector: 'Healthcare' },
  { ticker: 'TIMETECHNO', name: 'Time Technoplast', sector: 'Consumer' },
  { ticker: 'TNPL', name: 'Tamil Nadu Newsprint & Papers', sector: 'Consumer' },
  { ticker: 'TOTALTV', name: 'Total Transport Systems', sector: 'Logistics' },
  { ticker: 'TRANSGENE', name: 'Transgene Biotek', sector: 'Pharma' },
  { ticker: 'TTML', name: 'Tata Teleservices Maharashtra', sector: 'Telecom' },
  { ticker: 'TVTODAY', name: 'TV Today Network', sector: 'Media' },
  { ticker: 'UGROCAP', name: 'Ugro Capital', sector: 'NBFC' },
  { ticker: 'UNOMINDA', name: 'UNO Minda', sector: 'Auto' },
  { ticker: 'UNIPARTS', name: 'Uniparts India', sector: 'Engineering' },
  { ticker: 'USHAMART', name: 'Usha Martin', sector: 'Metals' },
  { ticker: 'UTIAMC', name: 'UTI Asset Management Company', sector: 'Capital Markets' },
  { ticker: 'VAKRANGEE', name: 'Vakrangee', sector: 'Consumer Tech' },
  { ticker: 'VAIBHAVGBL', name: 'Vaibhav Global', sector: 'Retail' },
  { ticker: 'VARDHACRLC', name: 'Vardhman Acrylics', sector: 'Chemicals' },
  { ticker: 'VDMDSTEEL', name: 'VDMD Steel', sector: 'Metals' },
  { ticker: 'VENUSREM', name: 'Venus Remedies', sector: 'Pharma' },
  { ticker: 'VIJAYA', name: 'Vijaya Diagnostic Centre', sector: 'Healthcare' },
  { ticker: 'VIKASLIFE', name: 'Vikas Lifecare', sector: 'Chemicals' },
  { ticker: 'VMART', name: 'V-Mart Retail', sector: 'Retail' },
  { ticker: 'VSTIND', name: 'VST Industries', sector: 'FMCG' },
  { ticker: 'WELSPUNLIV', name: 'Welspun Living', sector: 'Textiles' },
  { ticker: 'WINDMACHIN', name: 'Windsor Machines', sector: 'Engineering' },
  { ticker: 'WOCKPHARMA', name: 'Wockhardt', sector: 'Pharma' },
  { ticker: 'XCHANGING', name: 'Xchanging Solutions', sector: 'IT' },
  { ticker: 'YATHARTH', name: 'Yatharth Hospital & Trauma Care Services', sector: 'Healthcare' },
  { ticker: 'ZENSARTECH', name: 'Zensar Technologies', sector: 'IT' },
  { ticker: 'ZODJRDMKJ', name: 'Zodiac JRD-MKJ', sector: 'Consumer' },
  { ticker: 'ZUARI', name: 'Zuari Agro Chemicals', sector: 'Agrochem' },
  { ticker: 'ZYDUSWELL', name: 'Zydus Wellness', sector: 'FMCG' },
];

export const STOCK_UNIVERSE: StockInfo[] = [
  ...NIFTY_50,
  ...NIFTY_NEXT_50,
  ...NIFTY_MIDCAP_150,
  ...NIFTY_SMALLCAP_250,
];

export const UNIVERSE_BY_INDEX: Record<string, StockInfo[]> = {
  'Nifty 50': NIFTY_50,
  'Nifty Next 50': NIFTY_NEXT_50,
  'Nifty Midcap 150': NIFTY_MIDCAP_150,
  'Nifty Smallcap 250': NIFTY_SMALLCAP_250,
};

export function getNSSymbol(ticker: string): string {
  return `${ticker}.NS`;
}

export function findStock(query: string): StockInfo[] {
  const q = query.toLowerCase().trim();
  return STOCK_UNIVERSE.filter(
    (s) =>
      s.ticker.toLowerCase().includes(q) ||
      s.name.toLowerCase().includes(q) ||
      s.sector.toLowerCase().includes(q)
  ).slice(0, 10);
}

export function getStockInfo(ticker: string): StockInfo | undefined {
  return STOCK_UNIVERSE.find(
    (s) => s.ticker.toLowerCase() === ticker.toLowerCase()
  );
}
